name: DailySync
on:
  schedule:
    - cron: '0 14 * * 0,2,4' # 每周二、四、日晚上北京时间 10 点运行
  workflow_dispatch: # 允许我们手动点击运行测试
jobs:
  do-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install @supabase/supabase-js axios
      - name: Start Sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: node sync.js
